### ISSUE TITLE
autoform reactive labels

### ISSUE THREAD

**Issue by boustanihani** [anticoders/meteor-i18n#17]
I am using "just-i18n" with ["meteor-autoform"](https://github.com/aldeed/meteor-autoform) and I want my labels to be reactive when language changes. Assigning ```i18n('key')``` to the labels defined in my ["SimpleSchemas"](https://github.com/aldeed/meteor-simple-schema) did not help.

Isn't the global javascript function ```i18n()``` **supposed to be reactive** ??

I tried wrapping ```i18n()``` inside another global function ```trans()``` which returns a callback for ```i18n()``` and magically this fixed the problem. **I don't know why this helped** and if this is the correct way to do it ??!!

Here is my code:

```javascript
// Translate reactively
transr = function(key) {
    return function() {
        return i18n(key);
    };
};

Schema.user = new SimpleSchema({
    email: {
        type: String,
        label: transr('email'),
        regEx: SimpleSchema.RegEx.Email,
    },
    //...
});
```

P.S. I am new to reactive programming :)

**Comment by subhog** [comment]
As @Nemo64 pointed out, if you want SimpleSchema label to be reactive, you need to set it as a function. You don't need to define it separately, though, an inline definition will suffice:

    email: {
        type: String,
        label: function() {return i18n('email');},
        regEx: SimpleSchema.RegEx.Email,
    },
