### ISSUE TITLE
little helper, comes in handy

### ISSUE THREAD

**Issue by herrhelms** [anticoders/meteor-i18n#19]
just a thought for a little trick to share with the community or add as feature to your source. 
maybe you'll share it on your README.md 

In order to capitalize the first Character of any i18n string you can add your own little helper:
```UI.registerHelper('I18n',function(string) {
   return i18n(string).charAt(0).toUpperCase() + i18n(string).slice(1);
});```

note the use of UPPERCASED `I18n` instead of `i18n`

**Comment by dropfen** [comment]
Why do you not creating a Package? And use a better HelpersName like : *{{ Up str }} and {{ UP str }}* and not I18n (which actually means *Internationalization*)

**Comment by herrhelms** [comment]
I know what it means, thanks! It was just an idea to bundle it since you already provide a lowercased {{i18n "string"}}. To make a package out of it sounds like a good idea at first but then I think this adds too little to be a package on its own.

**Comment by dropfen** [comment]
@herrhelms look at this as a reference to small packages ;) 
https://github.com/meteorhacks/meteor-aggregate

**Comment by subhog** [comment]
I have to agree with @dropfen on this one. It's better to have numerous small packages that solve small problems in minimal, maintainable way.
